weights: yolov5/yolov5x.pt
cfg: ''
data: yolov5/data/data.yaml
hyp: ./yolov5/data/hyps/hyp.scratch.yaml
epochs: 30
batch_size: 64
imgsz: 512
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: ram
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 8
project: yolov5/RSNA_YOLO_Project
entity: null
name: Exp1
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
local_rank: -1
freeze: 0
save_dir: yolov5/RSNA_YOLO_Project/Exp1
